#!/bin/sh
#
# nodemgr Oracle Weblogic NodeManager service
#
# chkconfig:   345 85 15
# description: Oracle Weblogic NodeManager service
# The script needs to be saved as /etc/init.d/nodemgr and then issue chkconfig --add nodegr as root
# 10/06/2014 -- Nito@Qindel.ES

### BEGIN INIT INFO
# Provides: nodemgr
# Required-Start: $network $local_fs
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Oracle Weblogic NodeManager service.
# Description: Starts and stops Oracle Weblogic NodeManager.
### END INIT INFO

. /etc/rc.d/init.d/functions

SERVICE_NAME=nodemgr
export ORACLE_BASE=/u01/app/oracle
export NODEMANAGER_BASE=$ORACLE_BASE/runtime/nodemanager/$(hostname -s)
export NODEMANAGER_HOME=$NODEMANAGER_BASE
export NODEMANAGER_BIN=$NODEMANAGER_BASE/startNodeManager.sh
export DAEMON_USER=orafmw
PROCESS_STRING="^.* weblogic.NodeManager.*"
NODEMANAGER_LOCK="$NODEMANAGER_HOME/nodemanager.log.lck"

[ -r /etc/sysconfig/$SERVICE_NAME ] && . /etc/sysconfig/$SERVICE_NAME

PROGRAM="$NODEMANAGER_BIN > $NODEMANAGER_HOME/nodemanager.out 2>&1"
LOCKFILE="/var/lock/subsys/$SERVICE_NAME"


RETVAL=0

start() {
        OLDPID=`/usr/bin/pgrep -f "$PROCESS_STRING"`
        if [ ! -z "$OLDPID" ]; then
            echo "$SERVICE_NAME is already running (pid $OLDPID) !"
            exit
        fi

        echo -n $"Starting $SERVICE_NAME: "
	/bin/su $DAEMON_USER -c "$PROGRAM &"
	sleep .2

	/usr/bin/pgrep -f "$PROCESS_STRING" > /dev/null
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch $LOCKFILE
}

stop() {
        echo -n $"Stopping $SERVICE_NAME: "
        OLDPID=`/usr/bin/pgrep -f "$PROCESS_STRING"`
        if [ "$OLDPID" != "" ]; then
            /bin/kill -TERM $OLDPID
	    sleep .2
        else
            /bin/echo "$SERVICE_NAME is stopped"
        fi
        echo
        /bin/rm -f $NodeManagerLockFile
	/usr/bin/pgrep -f "$PROCESS_STRING" > /dev/null
	RETVAL=$((! $?))
        [ $RETVAL -eq 0 ] && rm -f $LOCKFILE
}

restart() {
        stop
        sleep 10
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|force-reload|reload)
        restart
        ;;
  condrestart|try-restart)
        [ -f $LOCKFILE ] && restart
        ;;
  status)
        OLDPID=`/usr/bin/pgrep -f "$PROCESS_STRING"`
        RETVAL=$?
        if [ "$OLDPID" != "" ]; then
            /bin/echo "$SERVICE_NAME is running (pid: $OLDPID)"
        else
            /bin/echo "$SERVICE_NAME is stopped"
        fi
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
        exit 1
esac

exit $RETVAL

